# Generated by Django 4.2.2 on 2023-06-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('day', 'time', 'title'), 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AddConstraint(
            model_name='titlerating',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='title_user_unique'),
        ),
    ]
