# Generated by Django 4.2.2 on 2023-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schedule_options_titlerating_title_user_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='titlerating',
            name='title_user_unique',
        ),
        migrations.AddConstraint(
            model_name='titlerating',
            constraint=models.UniqueConstraint(fields=('title', 'user'), name='title_user_unique', violation_error_message='fe'),
        ),
    ]
