# Generated by Django 4.2.2 on 2023-06-12 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_titlerating_title_user_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='titlerating',
            name='title_user_unique',
        ),
        migrations.AlterUniqueTogether(
            name='titlerating',
            unique_together={('title', 'user')},
        ),
    ]
