# Generated by Django 4.2.2 on 2023-06-12 16:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_titlerating_title_user_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageTitleRating',
            fields=[
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.title')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Средняя оценка')),
            ],
        ),
    ]
