# Generated by Django 4.2.2 on 2023-06-12 16:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_averagetitlerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagetitlerating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Средняя оценка'),
        ),
        migrations.AlterField(
            model_name='averagetitlerating',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='avg_rating', serialize=False, to='core.title'),
        ),
    ]
