# Generated by Django 4.2.2 on 2023-06-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_averagetitlerating_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagetitlerating',
            name='voters',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество проголосовавших'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='averagetitlerating',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='average_rating', serialize=False, to='core.title'),
        ),
        migrations.AlterField(
            model_name='titlerating',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='core.title', verbose_name='Тайтл'),
        ),
    ]
