# Generated by Django 4.2.2 on 2023-06-12 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_averagetitlerating_voters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('-create_time',), 'verbose_name': 'Тайтл', 'verbose_name_plural': 'Тайтлы'},
        ),
        migrations.RemoveField(
            model_name='title',
            name='alternative_title',
        ),
        migrations.AddField(
            model_name='title',
            name='original_title',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Оригинальное название'),
        ),
        migrations.CreateModel(
            name='Alternative_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_title', to='core.title')),
            ],
        ),
    ]
