# Generated by Django 4.2.2 on 2023-06-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_title_options_remove_title_alternative_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alternative_title',
            new_name='AlternativeTitle',
        ),
    ]
