# Generated by Django 4.2.2 on 2023-06-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_alternative_title_alternativetitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='episodes_realesed',
            new_name='episodes_released',
        ),
        migrations.AlterField(
            model_name='titlerating',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_rating', to='core.title', verbose_name='Тайтл'),
        ),
        migrations.AlterField(
            model_name='titleviews',
            name='ip',
            field=models.GenericIPAddressField(default='45.243.82.169', null=True),
        ),
        migrations.AlterField(
            model_name='titleviews',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_views', to='core.title'),
        ),
    ]
