# Generated by Django 4.2.2 on 2023-06-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Dislike'), (1, 'Like')]),
        ),
    ]
