# Generated by Django 4.2.2 on 2023-06-25 11:33

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_display_name_alter_user_age_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, max_length=128, null=True, quality=100, scale=None, size=[150, 150], upload_to='avatar/', verbose_name='Аватар'),
        ),
    ]
