# Generated by Django 4.2.2 on 2023-06-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.SmallIntegerField(blank=True, choices=[(-1, None), (0, 'female'), (1, 'male')], null=True, verbose_name='Пол'),
        ),
    ]
