# Generated by Django 4.2.2 on 2023-06-26 14:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubepost',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, max_length=128, quality=90, scale=None, size=[622, 350], upload_to='youtube_post', verbose_name='Фото'),
        ),
    ]
